### ISSUE TITLE
Design the UI

### ISSUE THREAD

**Issue by Findeton** [sequentech/new-ballot-verifier#3]
- [x] Review research ( mainly https://rke.abertay.ac.uk/ws/portalfiles/portal/14702506/Renaud_WhatDidIReallyVoteFor_Author_2018.pdf )
- [x] Create initial product design document ( https://docs.google.com/document/d/1bxH5tg85YO75QxUCi_Lz6jMoEXgup-kABCqmWQvXD-o/edit# )
- [x] Agree on the product design document with stakeholders
- [x] Create wireframes

**Comment by edulix** [comment]
The design is nearly finished. Final review/comments iteration is in progress, and after that tomorrow morning I'll review all feedback and finish the Design Document.

**Comment by edulix** [comment]
Marking the task as done. We have the initial design, of course this can be improved later. We will actually enlarge the circle of people that we will ask feedback to, but in the meantime we have already started to implement this design.
